apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-syab
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-syab@sha256:55d8ab65a964955331d581f77a4967ce82b88daf467a57228bc018b172de3e10
        name: my-nodejs
        resources: {}
status: {}
